// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8SBvXVQ8ako5-HqMLtjRgygE0pex6YjM',
    appId: '1:289483461768:web:4fb934251491989c7f3b3d',
    messagingSenderId: '289483461768',
    projectId: 'fitness-ai-app-53ba9',
    authDomain: 'fitness-ai-app-53ba9.firebaseapp.com',
    storageBucket: 'fitness-ai-app-53ba9.firebasestorage.app',
    measurementId: 'G-SQPSXHREJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-z_wVkW45GXf0-JFFfO2wMfdCb7WCWTs',
    appId: '1:289483461768:android:bcc2c9fb9090a9b47f3b3d',
    messagingSenderId: '289483461768',
    projectId: 'fitness-ai-app-53ba9',
    storageBucket: 'fitness-ai-app-53ba9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE-Bi0ZdDXEKJuNiIEBFCqyIc_WAhwKjw',
    appId: '1:289483461768:ios:16555a10affe135e7f3b3d',
    messagingSenderId: '289483461768',
    projectId: 'fitness-ai-app-53ba9',
    storageBucket: 'fitness-ai-app-53ba9.firebasestorage.app',
    iosBundleId: 'com.example.fitnessAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE-Bi0ZdDXEKJuNiIEBFCqyIc_WAhwKjw',
    appId: '1:289483461768:ios:16555a10affe135e7f3b3d',
    messagingSenderId: '289483461768',
    projectId: 'fitness-ai-app-53ba9',
    storageBucket: 'fitness-ai-app-53ba9.firebasestorage.app',
    iosBundleId: 'com.example.fitnessAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8SBvXVQ8ako5-HqMLtjRgygE0pex6YjM',
    appId: '1:289483461768:web:50f32809065941857f3b3d',
    messagingSenderId: '289483461768',
    projectId: 'fitness-ai-app-53ba9',
    authDomain: 'fitness-ai-app-53ba9.firebaseapp.com',
    storageBucket: 'fitness-ai-app-53ba9.firebasestorage.app',
    measurementId: 'G-G909BC6ETR',
  );
}
